[versions]
sakshi-sdk = "1.0.0-RC.0"

agp = "9.4.1"
mockk = "1.14.11"
kotlin = "2.4.20"
coroutines = "1.11.0"
androidx-core = "1.19.1"
androidx-annotation = "1.10.0"
junit-jupiter = "6.1.3"
junit-platform = "6.1.3"

[libraries]
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.37.0" }
