name: Question
description: Ask a question about Sakshi SDK usage or IPC integration.
title: "[QUESTION]: "
labels: ["question"]
assignees: [RajnishKMehta]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to ask or clarify?
    validations:
      required: true
