package rajnishkmehta.sakshi.sdk.api.models

import android.net.Uri

/**
 * Request payload sent by Camera application to Vault to initiate incremental audio/video synchronization.
 *
 * @property fileId Unique identifier generated by Camera for the audio/video recording.
 * @property uri Content Uri or file reference pointing to the active recording file.
 * @property mimeType MIME type of recording (e.g. "video/mp4", "audio/mp4").
 * @property startTimestampEpochMs Epoch timestamp in milliseconds when recording started.
 * @property metadata Optional key-value metadata accompanying the sync request.
 */
public data class AVSyncRequest(
    public val fileId: String,
    public val uri: Uri,
    public val mimeType: String?,
    public val startTimestampEpochMs: Long = System.currentTimeMillis(),
    public val metadata: Map<String, String> = emptyMap()
)
