package rajnishkmehta.sakshi.sdk.api.models

import android.net.Uri

/**
 * Request payload sent by Camera application to Vault to initiate incremental audio/video synchronization.
 *
 * @property fileId Unique identifier generated by Camera for the audio/video recording. Must contain only lowercase a-z, digits 0-9, underscore, or hyphen, and be between 8 and 128 characters long.
 * @property uri Content Uri or file reference pointing to the active recording file.
 * @property mediaType Media type of recording (e.g. "PHOTO", "VIDEO", "AUDIO", "OTHER").
 * @property fileExtension The file extension for the recording (e.g. "mp4", "m4a"). Must be between 1 and 12 characters long, not contain spaces, start/end with a dot, or contain slashes, backslashes, or ".." path traversal sequences.
 * @property startTimestampEpochMs Epoch timestamp in milliseconds when recording started.
 * @property metadata Optional key-value metadata accompanying the sync request.
 */
public data class AVSyncRequest(
    public val fileId: String,
    public val uri: Uri,
    public val mediaType: String,
    public val fileExtension: String,
    public val startTimestampEpochMs: Long = System.currentTimeMillis(),
    public val metadata: Map<String, String> = emptyMap()
)
