package rajnishkmehta.sakshi.sdk.api.models

import android.net.Uri

/**
 * Request payload sent by Camera application to Vault to initiate incremental video synchronization.
 *
 * @property fileId Unique identifier generated by Camera for the video recording.
 * @property uri Content Uri or file reference pointing to the active recording file.
 * @property mimeType MIME type of video (e.g. "video/mp4").
 * @property startTimestampEpochMs Epoch timestamp in milliseconds when recording started.
 * @property metadata Optional key-value metadata accompanying the video sync request.
 */
public data class VideoSyncRequest(
    public val fileId: String,
    public val uri: Uri,
    public val mimeType: String = "video/mp4",
    public val startTimestampEpochMs: Long = System.currentTimeMillis(),
    public val metadata: Map<String, String> = emptyMap()
)
