name: Build & Test

on:
  # Run automatically on pushes to main
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"
      - ".editorconfig"
      - ".gitattributes"
      - "docs/**"
      - ".github/ISSUE_TEMPLATE/**"

  # manual run
  workflow_dispatch:

# Cancel older runs when a newer commit is pushed
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Run Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout Repo
      - name: Checkout Repository
        uses: actions/checkout@v7

      # Install Java
      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      # Configure Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      # make gradlew executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build, lint and run all checks
      - name: Build & Test
        run: ./gradlew :sakshi-sdk:check :sakshi-sdk:assembleRelease
